<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AntDesign" Version="1.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.12.19" />
    <PackageVersion Include="Nito.AsyncEx.Coordination" Version="5.1.2" />
    <PackageVersion Include="Pathoschild.Http.FluentClient" Version="4.4.2" />
    <PackageVersion Include="SimpleBase" Version="5.6.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>
</Project>
